export  const CREATE_RATINGREVIEW_FAILURE ="CREATE_RATINGREVIEW_FAILURE"
export  const CREATE_RATINGREVIEW_REQUEST ="CREATE_RATINGREVIEW_REQUEST"
export  const CREATE_RATINGREVIEW_SUCCESS ="CREATE_RATINGREVIEW_SUCCESS"

export  const GET_RATINGREVIEW_REQUEST ="GET_RATINGREVIEW_REQUEST"
export  const GET_RATINGREVIEW_SUCCESS ="GET_RATINGREVIEW_SUCCESS"
export  const GET_RATINGREVIEW_FAILURE ="GET_RATINGREVIEW_FAILURE"



export  const UPDATE_RATINGREVIEW_REQUEST ="UPDATE_RATINGREVIEW_REQUEST"
export  const UPDATE_RATINGREVIEW_SUCCESS ="UPDATE_RATINGREVIEW_SUCCESS"
export  const UPDATE_RATINGREVIEW_FAILURE ="UPDATE_RATINGREVIEW_FAILURE"
